RuralCaravan/RuralCaravan/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from RuralCaravan import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fpo/', include('fpo.urls')),
    path('farmer/', include('farmer.urls')),
    path('farmer/api/', include('farmer.api.urls')),
    path('members/',include('members.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('', views.home),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

RuralCaravan/fpo/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from django.urls import path, include
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name = 'home'),
    path('logout/', views.logout_request, name='logout'),
    path('login/', views.login_request, name='login'),
    
    
    # path('plans/', views.plans_view, name = 'plans'),
    path('govtschemes/', views.govtschemes_view, name = 'govtschemes'),
    path('govtschemes/delete/<id>', views.govtschemes_delete, name = 'govtschemes'),
    path('govtschemes/update/<id>', views.govtschemes_update, name = 'govtschemes-update'),

	
	#added by aditya
	path('govtschemes/<int:id>', views.govtschemes_single, name='govtschemes_single'),
    path('govtschemes/<int:id>/add/', views.govtschemes_single_add, name='govtschemes_single_add'),
	
	path('statistics/', views.fpo_statistics, name='fpo_statistics'),


    path('send_message/', views.send_message, name='send_message'),
    path('predict_crop/', views.predict_crop, name="predict_crop"),


    path('redeem/', views.redeem, name="redeem"),
    # path('populate_farmers/', views.populate_farmers, name='populate_farmers'),
    path('mark_rsvp/', views.mark_rsvp, name='mark_rsvp'),
    path('mark_attendance/', views.mark_attendance, name='mark_attendance'),
    path('mark_redeemed/', views.mark_redeemed, name='mark_redeemed'),
	#added by aditya
	
	
    path('meetings/<id>/', views.detail_meetings, name = 'fpo-detail_meetings'),
    path('meetings/', views.meetings_view, name = 'meetings'),
    path('meetings/update/<id>', views.meetings_update, name = 'meetings-update'),
    path('meetings/delete/<id>', views.meetings_delete, name = 'meetings-delete'),

    path('plans/', views.plans_view, name = 'plans'),
    path('plans/update/<id>', views.plans_update, name = 'plans-update'),
    path('plans/delete/<id>', views.plans_delete, name = 'plans-delete'),
    path('plans/toggle/<id>', views.plans_toggle, name = 'plans-toggle'),
    path('plans/detail/<id>', views.plans_detail, name = 'plans-detail'),
    
    path('plans/api/data_village_count', views.data_village_count, name = 'plans-data-village-count'),
    path('plans/api/data_village_quantity', views.data_village_quantity, name = 'plans-data-village-quantity'),
    path('plans/detail/<id1>/delete/<id2>', views.plan_del_product, name = 'plan_del_product'),
    path('plans/detail/<id>/add/', views.plan_add_product, name = 'plan_add_product'),
    path('plans/subs', views.add_FarmerCropMap, name = 'add_FarmerCropMap'),

    path('products/', views.products_view, name='products'),
    path('products/update/<id>', views.products_update, name='products-update'),
    path('products/delete/<id>', views.products_delete, name='products-delete'),
    path('products/detail/<id>', views.products_detail, name='products-detail'),
    path('products/toggle/<id>', views.products_toggle, name='products-toggle'),
    

    path('orders/', views.orders_view, name='orders'),
    path('orders/delete/<id>', views.orders_delete, name='orders-delete'),
    path('orders/delivered/<id>', views.orders_delivered_toggle, name='orders-toggle-delivered'),
    path('orders/paid/<id>', views.orders_paid_toggle, name='orders-toggle-paid'),

    
    # path('plan/', views.plan, name = 'fpo-plan'),
    # path('meeting/', views.meeting, name = 'fpo-meeting'),
    # path('govt_schemes/', views.govt_schemes, name = 'fpo-govt_schemes'),
   


] 

RuralCaravan/farmer/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.conf import settings
from django.db.models.signals import post_save, post_delete, pre_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token
from django.utils import timezone
from datetime import datetime
from ckeditor.fields import RichTextField
from farmer.SMSservice import sms
import random


class MyUserProfileManager(BaseUserManager):   ## not a Model
    def create_user(self, username, category='F', password=None):
        if not username:
            raise ValueError("Username required")
        if not category:
            raise ValueError("Category required")

        user = self.model(username=username, category=category)

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, category='A', password=None ):
        user = self.create_user(username=username, category=category, password=password)

        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.is_superviser = True
        user.save(using=self._db)

        return user


class UserProfile(AbstractBaseUser):
    username = models.CharField(max_length=50, unique=True)
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)

    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superviser = models.BooleanField(default=False)

    CATEGORIES = (
        ('A', 'FPO Admin'),
        ('L', 'Leader'),
        ('F', 'Farmer with Smart Phone'),
        ('P', 'Farmer with Feature Phone'),
        ('N', 'Farmer with No Phone'),
    )

    category = models.CharField(max_length=10, choices=CATEGORIES)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['category', ]

    objects = MyUserProfileManager()

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)
        Ewallet.objects.create(user=instance)


class Products(models.Model):
    name = models.CharField(max_length=100)

    CATEGORY = (
        ('SED', 'Seeds'),
        ('FER', 'Fertilizer'),
        ('PES', 'Pesticide'),
        ('EQP', 'Equipment'),
        ('OTH', 'Others'),
    )
    category = models.CharField(max_length=3, choices=CATEGORY)
    rate = models.FloatField()
    description = RichTextField(null=True, blank=True)
    image = models.ImageField(upload_to='images/products_images/', null=True, blank=True)
    available = models.BooleanField(default=True)

    def __str__(self):
        ID = str(self.id)
        return ID + " " + self.name

class Crops(models.Model):
    code = models.CharField(max_length=6)
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    max_cap = models.FloatField()
    current_amount = models.FloatField(default=0)
    weigth_per_land = models.FloatField()
    guidance = RichTextField(null=True, blank=True)
    live = models.BooleanField()
    image = models.ImageField(upload_to='images/crop_images', null=True, blank=True)
    products = models.ManyToManyField(Products, null=True, blank=True)
    subscribers = models.IntegerField(default=0)
    investment_requirements = models.TextField(null=True, blank=True, default=None)
    facilities = models.TextField(null=True, blank=True, default=None)

    def __str__(self):
        return self.name


class Farmer(models.Model):
    user = models.OneToOneField(UserProfile, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    aadhar = models.CharField(max_length=12, null=True, blank=True)
    contact = models.CharField(max_length=10)
    village = models.CharField(max_length=100)
    district = models.CharField(max_length=100)
    pin = models.CharField(max_length=6, null=True, blank=True)
    photo = models.ImageField(upload_to='images/profile_photos/', null=True, blank=True)

    ##Extra changes by Aniket
    govt_schemes = models.ManyToManyField('Govt', blank=True)
    engagement = models.FloatField(default=0.0)

    def __str__(self):
        return self.user.username + '-' +  self.first_name

@receiver(post_save, sender='farmer.Farmer')
def create_meeting_token(sender, instance=None, created=False, **kwargs):
    if created:
        try:
            meetings = Meetings.objects.filter(date__gte=datetime.now().date())
            for meeting in meetings:
                MeetingToken(token_number=int(str(random.randint(100000, 999999)) + str(instance.id)), meeting=meeting, farmer=instance).save()
        except:
            raise Exception('Could not generate Meeting tokens for the farmer')

class FarmerCropMap(models.Model):
    farmer = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    crop = models.ForeignKey(Crops, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    landarea = models.FloatField(default=0)

    class Meta:
        unique_together = (("farmer", "crop"),)


class Leader(models.Model):
    user = models.OneToOneField(UserProfile, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    aadhar = models.CharField(max_length=12, null=True, blank=True)
    contact = models.CharField(max_length=10)
    village = models.CharField(max_length=100)
    district = models.CharField(max_length=100)
    pin = models.IntegerField()
    photo = models.ImageField(upload_to='images/profile_photos/', null=True, blank=True)
    profession = models.CharField(max_length=100, null=True, blank=True)
    farmers = models.ManyToManyField(UserProfile, related_name='downlines', null=True, blank=True)

    def __str__(self):
        return self.user.username + '-' + self.first_name



class BankDetails(models.Model):
    user = models.OneToOneField(UserProfile, on_delete=models.CASCADE)
    acc_no = models.CharField(max_length=15)
    ifsc = models.CharField(max_length=11)



class Land(models.Model):
    owner = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    area = models.CharField(max_length=10)

    SOIL_CATEGORY = (
        ('A', 'Type A'),
        ('B', 'Type B'),
        ('C', 'Type C'),
    )

    soil = models.CharField(max_length=3, choices=SOIL_CATEGORY)
    address = models.CharField(max_length=150)



class Meetings(models.Model):
    organiser = models.CharField(max_length=50)
    agenda = models.CharField(max_length=100)
    venue = models.CharField(max_length=150)
    date = models.DateField()
    time = models.TimeField()
    description = RichTextField(null=True, blank=True)
    photo = models.ImageField(upload_to='images/meeting_photos/', null=True, blank=True)

    def __str__(self):
        return self.agenda

@receiver(post_save, sender='farmer.Meetings')
def send_sms_notification(sender, instance=None, created=False, **kwargs):
    if created:
        agenda = instance.agenda
        organiser = instance.organiser
        date = instance.date.strftime("%d/%m/%Y")
        message = "A meeting on \"" + agenda + "\" by " + organiser + " is scheduled on " + date
        contacts = Contact.objects.filter(verification_status=True)
        for contact in contacts:
            try:
                sms.send_message("+91"+contact.number, sms.TWILIO_NUMBER, message)
            except:
                print("unable to send SMS")


class Orders(models.Model):
    TYPE = (
        ('COD', 'Cash on Delivery'),
        ('UPI', 'UPI Payment'),
        ('CAS', 'Pay at FPO office'),
        ('PEW', 'Pay with E-Wallet'),
    )
    type = models.CharField(max_length=3, choices=TYPE)
    item = models.ForeignKey(Products, on_delete=models.SET_DEFAULT, default=-1)
    buyer = models.ForeignKey(UserProfile, on_delete=models.PROTECT)
    price = models.FloatField()
    rate = models.FloatField()
    quantity = models.IntegerField()
    is_paid = models.BooleanField(default=False)
    is_delivered = models.BooleanField(default=False)
    date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.buyer.username + " - " + self.item.name


class Produce(models.Model):
    crop = models.ForeignKey(Crops, on_delete=models.PROTECT)
    amount = models.FloatField()
    amountsold = models.FloatField(default=0)
    date = models.DateTimeField(default=timezone.now)
    land = models.ForeignKey(Land, models.SET_NULL, null=True, blank=True)
    quality = models.BooleanField()
    owner = models.ForeignKey(UserProfile, on_delete=models.PROTECT)
    income = models.FloatField(default=0)


    def __str__(self):
        return self.owner.username + " " + self.crop.name


class Kart(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    item = models.ForeignKey(Products, on_delete=models.SET_DEFAULT, default=-1)
    quantity = models.IntegerField()

    def __str__(self):
        return self.user.username + " " + self.item.name

class Ewallet(models.Model):
    user = models.OneToOneField(UserProfile, on_delete=models.CASCADE)
    amount = models.FloatField(default=0)

    def __str__(self):
        return self.user.username

class ew_transaction(models.Model):
    refno = models.CharField(max_length=20)
    user = models.ForeignKey(UserProfile, on_delete=models.PROTECT)
    amount = models.FloatField()
    date = models.DateTimeField(default=timezone.now)
    currrent_amount = models.FloatField(default=0)
    description = models.CharField(max_length=200)

RuralCaravan/fpo/forms.py
from django import forms 
from farmer.models import *
from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import 


class FarmerForm(forms.ModelForm):
    # create meta class 
    class Meta: 
        # specify model to be used 
        model = Farmer
  
        # specify fields to be used 
        fields = [ 
            "user",             
            "first_name",           
            "last_name",            
            "aadhar",               
            "contact",               
            "village",               
            "district",               
            "pin",               
            "photo",              
        ] 

class DateInput(forms.DateInput):
    input_type = 'date'
class TimeInput(forms.TimeInput):
    input_type = 'time'

class MeetingsForm(forms.ModelForm): 
  
    # create meta class 
    class Meta: 
        # specify model to be used 
        model = Meetings
  
        # specify fields to be used 
        fields = [ 
            "organiser",        
            "agenda",        
            "venue",        
            "date", 
            "time", 
            "description", 
            "photo", 
        ]
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'time': forms.TimeInput(attrs={'type': 'time'})
        }

class GovtForm(forms.ModelForm):
    # create meta class 
    class Meta:
        # specify model to be used 
        model = Govt
  
        # specify fields to be used 
        fields = [ 
            "name",
            "description",
        ]

class CropsForm(forms.ModelForm):
    # create meta class 
    class Meta: 
        # specify model to be used 
        model = Crops
  
        # specify fields to be used 
        fields = [ 
            "code",
            "name",   
            "type", 
            "max_cap", 
            "current_amount", 
            "weigth_per_land", 
            "guidance", 
            "live", 
            "products",
            "investment_requirements",
            "facilities",
            "subscribers",
            "image"
        ]

        widgets = {
            "products": forms.widgets.CheckboxSelectMultiple()
        }


class ProductsForm(forms.ModelForm):
    # create meta class
    class Meta:
        # specify model to be used
        model = Products

        # specify fields to be used
        fields = '__all__'


class FarmerCropMapForm(forms.ModelForm):
    # create meta class
    class Meta:
        # specify model to be used
        model = FarmerCropMap

        # specify fields to be used
        fields = '__all__'
        
class OrdersForm(forms.ModelForm):
    # create meta class
    class Meta:
        # specify model to be used
        model = Orders

        # specify fields to be used
        fields = '__all__'
class plan_add_productForm(forms.Form):
    # create meta class
    ID = forms.IntegerField()              

RuralCaravan/fpo/templates/fpo/add.html
<form method="POST" enctype="multipart/form-data"> 
  
    <!-- Security token -->
    {% csrf_token %} 
  
    <!-- Using the formset -->
    {{ form.as_p }} 
    <!-- {{ form.as_p }}  -->
    
      
    <input type="submit" value="Submit"> 
</form>

RuralCaravan/fpo/templates/fpo/add_meeting.html
 <!--Grid column-->
          <div class="col-lg-6 col-md-12" style="padding-top:4%">
			<!--Card-->
            <div class="card">

              <!--Card content-->
              <div class="card-body">

                <!-- Form -->
                <form method="POST" enctype="multipart/form-data">
                  <!-- Heading -->
                  {% csrf_token %}
                  <h3 class="dark-grey-text text-center">
                    <strong>ADD A MEETING</strong>
                  </h3>
                  <hr>

                  <div class="md-form">
				  <i class="far fa-user-circle prefix green-text"></i>

                    <input type="text"  class="form-control" name="organiser" maxlength="200" required id="id_organiser">
                    <label class="required" for="id_organiser">Enter Organiser</label>
                  </div>
                  <div class="md-form">
				  <i class="fas fa-check-square prefix green-text"></i>

                    <input type="text"  class="form-control" name="agenda" maxlength="200" required id="id_agenda">
                    <label for="id_agenda" class="required"> Enter Agenda</label>
                  </div>
                  <div class="md-form">
				  <i class="fas fa-map-marker-alt prefix green-text"></i>

                    <input type="text" class="form-control" name="venue" maxlength="200" required id="id_venue">
                    <label class="required" for="id_venue">Enter Venue</label>
                  </div>
                  <div class="md-form">
				  <i class="fas fa-calendar-alt prefix green-text"></i>

                    <input type="text" name="date"  class="form-control" size="10" required id="id_date" >
                    <label class="required" for="id_date">Enter Date in this format (YYYY-MM-DD)</label>
                  </div>
                  <div class="md-form">
				  <i class="far fa-clock prefix green-text"></i>

                    <input type="text" name="time"  class="form-control"  size="8" required id="id_time">
                    <label class="required" for="id_time">Enter Time in this format (HH:MM:SS)</label>
                  </div>


                  <div class="md-form">
                    <i class="fas fa-pencil-alt prefix green-text"></i>
                    <textarea   type="text"  class="md-textarea" name="description" cols="40" rows="10" required id="id_description"></textarea>
                    <label class="required" for="id_description">Enter Description</label>
                  </div>
                  <div class="form-row field-photo">




              </div>

                  <div class="text-center">
                    <button class="btn btn-green" type="submit" value="Submit">ADD</button>

                  </div>

                  <!-- {{ form }} -->
                  <!-- <input type="submit" value="Submit">  -->
                </form>

                <!-- Form -->

              </div>

            </div>

          </div>
          <!--/Grid column-->


        </div>
        <!--/Grid row-->

RuralCaravan/fpo/templates/fpo/test_add.html
<form method="POST" enctype="multipart/form-data"> 
  
    <!-- Security token -->
    {% csrf_token %} 
  
    <!-- Using the formset -->
    {{ form.as_p }} 
    
      
    <input type="submit" value="Submit"> 
</form> 

RuralCaravan/fpo/templates/fpo/update_meeting.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Meetings</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <!--  custom styles  -->
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
     <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    <style type="text/css">

      html,
      body,
      header,
      .carousel {
        height: 60vh;
      }

      @media (max-width: 740px) {
        html,
        body,
        header,
        .carousel {
          height: 100vh;
        }
      }

      @media (min-width: 800px) and (max-width: 850px) {
        html,
        body,
        header,
        .carousel {
          height: 100vh;
        }
      }

      @media (min-width: 800px) and (max-width: 850px) {
              .navbar:not(.top-nav-collapse) {
                  background:#295e10!important;
              }
          }

    </style>
</head>

<body>

  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand" href="{% url 'home' %}">
        <strong>FPO PORTAL</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'meetings' %}" >Meetings</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'plans' %}">Plans</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'govtschemes' %}" >Government Schemes</a>
          </li>
             <li class="nav-item">
            <a class="nav-link" href="{% url 'produce' %}" >Production</a>
          </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'FPOLedger'%}">Ledger</a>
            </li>
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
            <li class="nav-item">
            <a href="{% url 'add_user' %}" class="nav-link" data-toggle="tooltip" title="Add New User">
             <i class="fas fa-user-plus"></i>
            </a>
          </li>
             <li class="nav-item">
            <a href="{% url 'transaction'%}" class="nav-link" data-toggle="tooltip" title="Transactions">
             <i class="fas fa-rupee-sign"></i>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'orders' %}" class="nav-link" data-toggle="tooltip" title="Orders">
             <i class="fas fa-shopping-cart"></i>
            </a>
          </li>
             <li class="nav-item">
            <a href="{% url 'products' %}" class="nav-link" data-toggle="tooltip" title="Products">
             <i class="fas fa-shopping-basket"></i>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'fpo_statistics' %}" class="nav-link" data-toggle="tooltip" title="Statistics">
             <i class="fas fa-chart-bar"></i>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'members' %}" class="nav-link border border-light rounded"
             >
              <i class="fas fa-user"></i>Members
            </a>
          </li>
		  <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}" >Logout</a>
          </li>


        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->



  <!--Main layout-->
  <main style="padding-top:10%">
    <div class="container" >


        <!--Section: Main features & Quick Start-->
      <section style="padding-bottom:5%">
<form method="POST" enctype="multipart/form-data">

    <!-- Security token -->
    {% csrf_token %}

 <div class="col-lg-12 col-md-12">
			<!--Card-->
            <div class="card">

              <!--Card content-->
              <div class="card-body">

                <h3 class="dark-grey-text text-center">
                    <strong>UPDATE A MEETING</strong>
                  </h3>
                  <hr>
                <div class="md-form form-inline">

                    <i class="far fa-user-circle prefix green-text"></i>
                   <input type="text"  class="form-control" name="organiser" maxlength="50" required id="id_name" value="{{form.organiser.value}}"/>

                  </div>
                <div class="md-form form-inline">

                    <i class="fas fa-check-square prefix green-text"></i>
                   <input type="text"  class="form-control" name="agenda" maxlength="100" required id="id_agenda" value="{{form.agenda.value}}"/>

                  </div>
                   <div class="md-form form-inline">

                    <i class="fas fa-map-marker-alt prefix green-text"></i>
                   <input type="text"  class="form-control" name="venue" maxlength="150" required id="id_venue" value="{{form.venue.value}}"/>

                  </div>
                    <div class="md-form form-inline">

                    <i class="fas fa-calendar-alt prefix green-text"></i>
                   {{form.date}}

                  </div>
                    <div class="md-form form-inline">

                    <i class="far fa-clock prefix green-text"></i>
                        {{form.time}}

                  </div>

                    <div class="md-form">
                      <div>

                          <p><strong>Enter Description:</strong></p>
                      </div>


                    <textarea   type="text"  class="md-textarea" name="description" cols="40" rows="10">
                        {{form.description.value}}
                    </textarea>



                </div>


                  <div class="text-center">
                    <button class="btn btn-green" type="submit" value="Submit">SUBMIT</button>

                  </div>
                   </div> </div> </div>


</form>



      </section>
    </div>
  </main>
  <!--Main layout-->

  <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn" >



    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2020 Copyright:
  Rural Caravan
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
      <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    //new WOW().init();
  </script>
<script>
        CKEDITOR.replace('description');

    </script>
</body>

</html>