RuralCaravan/RuralCaravan/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from RuralCaravan import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fpo/', include('fpo.urls')),
    path('farmer/', include('farmer.urls')),
    path('farmer/api/', include('farmer.api.urls')),
    path('members/',include('members.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('', views.home),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

RuralCaravan/fpo/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from django.urls import path, include
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name = 'home'),
    path('logout/', views.logout_request, name='logout'),
    path('login/', views.login_request, name='login'),
    
    
    # path('plans/', views.plans_view, name = 'plans'),
    path('govtschemes/', views.govtschemes_view, name = 'govtschemes'),
    path('govtschemes/delete/<id>', views.govtschemes_delete, name = 'govtschemes'),
    path('govtschemes/update/<id>', views.govtschemes_update, name = 'govtschemes-update'),

	
	#added by aditya
	path('govtschemes/<int:id>', views.govtschemes_single, name='govtschemes_single'),
    path('govtschemes/<int:id>/add/', views.govtschemes_single_add, name='govtschemes_single_add'),
	
	path('statistics/', views.fpo_statistics, name='fpo_statistics'),


    path('send_message/', views.send_message, name='send_message'),
    path('predict_crop/', views.predict_crop, name="predict_crop"),


    path('redeem/', views.redeem, name="redeem"),
    # path('populate_farmers/', views.populate_farmers, name='populate_farmers'),
    path('mark_rsvp/', views.mark_rsvp, name='mark_rsvp'),
    path('mark_attendance/', views.mark_attendance, name='mark_attendance'),
    path('mark_redeemed/', views.mark_redeemed, name='mark_redeemed'),
	#added by aditya
	
	
    path('meetings/<id>/', views.detail_meetings, name = 'fpo-detail_meetings'),
    path('meetings/', views.meetings_view, name = 'meetings'),
    path('meetings/update/<id>', views.meetings_update, name = 'meetings-update'),
    path('meetings/delete/<id>', views.meetings_delete, name = 'meetings-delete'),

    path('plans/', views.plans_view, name = 'plans'),
    path('plans/update/<id>', views.plans_update, name = 'plans-update'),
    path('plans/delete/<id>', views.plans_delete, name = 'plans-delete'),
    path('plans/toggle/<id>', views.plans_toggle, name = 'plans-toggle'),
    path('plans/detail/<id>', views.plans_detail, name = 'plans-detail'),
    
    path('plans/api/data_village_count', views.data_village_count, name = 'plans-data-village-count'),
    path('plans/api/data_village_quantity', views.data_village_quantity, name = 'plans-data-village-quantity'),
    path('plans/detail/<id1>/delete/<id2>', views.plan_del_product, name = 'plan_del_product'),
    path('plans/detail/<id>/add/', views.plan_add_product, name = 'plan_add_product'),
    path('plans/subs', views.add_FarmerCropMap, name = 'add_FarmerCropMap'),

    path('products/', views.products_view, name='products'),
    path('products/update/<id>', views.products_update, name='products-update'),
    path('products/delete/<id>', views.products_delete, name='products-delete'),
    path('products/detail/<id>', views.products_detail, name='products-detail'),
    path('products/toggle/<id>', views.products_toggle, name='products-toggle'),
    

    path('orders/', views.orders_view, name='orders'),
    path('orders/delete/<id>', views.orders_delete, name='orders-delete'),
    path('orders/delivered/<id>', views.orders_delivered_toggle, name='orders-toggle-delivered'),
    path('orders/paid/<id>', views.orders_paid_toggle, name='orders-toggle-paid'),

    
    # path('plan/', views.plan, name = 'fpo-plan'),
    # path('meeting/', views.meeting, name = 'fpo-meeting'),
    # path('govt_schemes/', views.govt_schemes, name = 'fpo-govt_schemes'),
   


] 

RuralCaravan/members/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('member_page/add_farmer', views.add_farmer, name = 'add_farmer'),
    path('member_page/view_farmer/<id>/', views.detail_farmer, name = 'detail_farmer'),
    path('member_page/edit_farmer/<id>', views.update_farmer, name = 'update_farmer'),
    path('member_page/delete_farmer/<id>', views.delete_farmer, name = 'delete_farmer'),
    
    path('member_page/add_leader', views.add_leader, name = 'add_leader'),
    path('member_page/view_leader/<id>/', views.detail_leader, name = 'detail_leader'),
    path('member_page/edit_leader/<id>', views.update_leader, name = 'update_leader'),
    path('member_page/delete_leader/<id>', views.delete_leader, name = 'delete_leader'),

    path('member_page/add_user', views.add_user, name='add_user'),
       
    # path('farmer_profile/', views.farmer_profile, name = 'farmer_profile'),
    # path('leader_profile/', views.leader_profile, name = 'leader_profile'),
    path('member_page/', views.member_page, name = 'members'),

    path('member_page/view_leader/<id1>/delete/<id2>', views.leader_del_farmer, name = 'leader_del_farmer'),
    path('member_page/view_leader/<id>/add/', views.leader_add_farmer, name = 'leader_add_farmer'),

    path('member_page/view_farmer/<id>/bank/', views.bank_add_farmer, name='bank_add_farmer'),
    path('member_page/view_farmer/<id>/land/', views.land_add_farmer, name='land_add_farmer'),
    path('member_page/view_farmer/<id>/plan/', views.plan_add_farmer, name='plan_add_farmer'),

    path('member_page/fpoledger', views.FPOLedger_page, name='FPOLedger'),
    path('member_page/fpoledger/add', views.add_FPOLedger, name = 'add_FPOLedger'),
    path('member_page/fpoledger/delete/<id>', views.del_FPOLedger, name = 'del_FPOLedger'),

    path('member_page/produce',views.produce_page,name='produce'),
    path('member_page/produce/add', views.add_Produce, name = 'add_Produce'),
    path('member_page/produce/delete/<id>', views.del_Produce, name = 'del_Produce'),

    path('member_page/transaction', views.view_transaction, name = 'transaction'),
    path('member_page/transaction/add', views.add_transaction, name = 'add_transaction'),
    path('member_page/transaction/delete/<id>', views.del_transaction, name = 'del_transaction'),

    path('member_page/orders/', views.orders_view, name='orders'),
    path('member_page/orders/add', views.orders_add, name = 'orders-add'),
    path('member_page/orders/edit/<id>', views.orders_edit, name = 'orders-edit'),
    path('member_page/orders/delete/<id>', views.orders_delete, name='orders-delete'),
    path('member_page/orders/delivered/<id>', views.orders_delivered_toggle, name='orders-toggle-delivered'),
    path('member_page/orders/paid/<id>', views.orders_paid_toggle, name='orders-toggle-paid'),
    #path('transaction/edit/<id>', views.del_transaction, name = 'edit_transaction'),
    # path('plan/', views.plan, name = 'fpo-plan'),
    # path('meeting/', views.meeting, name = 'fpo-meeting'),
    # path('govt_schemes/', views.govt_schemes, name = 'fpo-govt_schemes'),
    #path('orders/',views.orders, name= 'order')

]

RuralCaravan/farmer/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.conf import settings
from django.db.models.signals import post_save, post_delete, pre_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token
from django.utils import timezone
from datetime import datetime
from ckeditor.fields import RichTextField
from farmer.SMSservice import sms
import random


class MyUserProfileManager(BaseUserManager):   ## not a Model
    def create_user(self, username, category='F', password=None):
        if not username:
            raise ValueError("Username required")
        if not category:
            raise ValueError("Category required")

        user = self.model(username=username, category=category)

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, category='A', password=None ):
        user = self.create_user(username=username, category=category, password=password)

        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.is_superviser = True
        user.save(using=self._db)

        return user


class UserProfile(AbstractBaseUser):
    username = models.CharField(max_length=50, unique=True)
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)

    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superviser = models.BooleanField(default=False)

    CATEGORIES = (
        ('A', 'FPO Admin'),
        ('L', 'Leader'),
        ('F', 'Farmer with Smart Phone'),
        ('P', 'Farmer with Feature Phone'),
        ('N', 'Farmer with No Phone'),
    )

    category = models.CharField(max_length=10, choices=CATEGORIES)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['category', ]

    objects = MyUserProfileManager()

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)
        Ewallet.objects.create(user=instance)


class Products(models.Model):
    name = models.CharField(max_length=100)

    CATEGORY = (
        ('SED', 'Seeds'),
        ('FER', 'Fertilizer'),
        ('PES', 'Pesticide'),
        ('EQP', 'Equipment'),
        ('OTH', 'Others'),
    )
    category = models.CharField(max_length=3, choices=CATEGORY)
    rate = models.FloatField()
    description = RichTextField(null=True, blank=True)
    image = models.ImageField(upload_to='images/products_images/', null=True, blank=True)
    available = models.BooleanField(default=True)

    def __str__(self):
        ID = str(self.id)
        return ID + " " + self.name

class Crops(models.Model):
    code = models.CharField(max_length=6)
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    max_cap = models.FloatField()
    current_amount = models.FloatField(default=0)
    weigth_per_land = models.FloatField()
    guidance = RichTextField(null=True, blank=True)
    live = models.BooleanField()
    image = models.ImageField(upload_to='images/crop_images', null=True, blank=True)
    products = models.ManyToManyField(Products, null=True, blank=True)
    subscribers = models.IntegerField(default=0)
    investment_requirements = models.TextField(null=True, blank=True, default=None)
    facilities = models.TextField(null=True, blank=True, default=None)

    def __str__(self):
        return self.name


class Farmer(models.Model):
    user = models.OneToOneField(UserProfile, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    aadhar = models.CharField(max_length=12, null=True, blank=True)
    contact = models.CharField(max_length=10)
    village = models.CharField(max_length=100)
    district = models.CharField(max_length=100)
    pin = models.CharField(max_length=6, null=True, blank=True)
    photo = models.ImageField(upload_to='images/profile_photos/', null=True, blank=True)

    ##Extra changes by Aniket
    govt_schemes = models.ManyToManyField('Govt', blank=True)
    engagement = models.FloatField(default=0.0)

    def __str__(self):
        return self.user.username + '-' +  self.first_name

@receiver(post_save, sender='farmer.Farmer')
def create_meeting_token(sender, instance=None, created=False, **kwargs):
    if created:
        try:
            meetings = Meetings.objects.filter(date__gte=datetime.now().date())
            for meeting in meetings:
                MeetingToken(token_number=int(str(random.randint(100000, 999999)) + str(instance.id)), meeting=meeting, farmer=instance).save()
        except:
            raise Exception('Could not generate Meeting tokens for the farmer')

class FarmerCropMap(models.Model):
    farmer = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    crop = models.ForeignKey(Crops, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    landarea = models.FloatField(default=0)

    class Meta:
        unique_together = (("farmer", "crop"),)


class Leader(models.Model):
    user = models.OneToOneField(UserProfile, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    aadhar = models.CharField(max_length=12, null=True, blank=True)
    contact = models.CharField(max_length=10)
    village = models.CharField(max_length=100)
    district = models.CharField(max_length=100)
    pin = models.IntegerField()
    photo = models.ImageField(upload_to='images/profile_photos/', null=True, blank=True)
    profession = models.CharField(max_length=100, null=True, blank=True)
    farmers = models.ManyToManyField(UserProfile, related_name='downlines', null=True, blank=True)

    def __str__(self):
        return self.user.username + '-' + self.first_name



class BankDetails(models.Model):
    user = models.OneToOneField(UserProfile, on_delete=models.CASCADE)
    acc_no = models.CharField(max_length=15)
    ifsc = models.CharField(max_length=11)



class Land(models.Model):
    owner = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    area = models.CharField(max_length=10)

    SOIL_CATEGORY = (
        ('A', 'Type A'),
        ('B', 'Type B'),
        ('C', 'Type C'),
    )

    soil = models.CharField(max_length=3, choices=SOIL_CATEGORY)
    address = models.CharField(max_length=150)



class Meetings(models.Model):
    organiser = models.CharField(max_length=50)
    agenda = models.CharField(max_length=100)
    venue = models.CharField(max_length=150)
    date = models.DateField()
    time = models.TimeField()
    description = RichTextField(null=True, blank=True)
    photo = models.ImageField(upload_to='images/meeting_photos/', null=True, blank=True)

    def __str__(self):
        return self.agenda

@receiver(post_save, sender='farmer.Meetings')
def send_sms_notification(sender, instance=None, created=False, **kwargs):
    if created:
        agenda = instance.agenda
        organiser = instance.organiser
        date = instance.date.strftime("%d/%m/%Y")
        message = "A meeting on \"" + agenda + "\" by " + organiser + " is scheduled on " + date
        contacts = Contact.objects.filter(verification_status=True)
        for contact in contacts:
            try:
                sms.send_message("+91"+contact.number, sms.TWILIO_NUMBER, message)
            except:
                print("unable to send SMS")


class Orders(models.Model):
    TYPE = (
        ('COD', 'Cash on Delivery'),
        ('UPI', 'UPI Payment'),
        ('CAS', 'Pay at FPO office'),
        ('PEW', 'Pay with E-Wallet'),
    )
    type = models.CharField(max_length=3, choices=TYPE)
    item = models.ForeignKey(Products, on_delete=models.SET_DEFAULT, default=-1)
    buyer = models.ForeignKey(UserProfile, on_delete=models.PROTECT)
    price = models.FloatField()
    rate = models.FloatField()
    quantity = models.IntegerField()
    is_paid = models.BooleanField(default=False)
    is_delivered = models.BooleanField(default=False)
    date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.buyer.username + " - " + self.item.name


class Produce(models.Model):
    crop = models.ForeignKey(Crops, on_delete=models.PROTECT)
    amount = models.FloatField()
    amountsold = models.FloatField(default=0)
    date = models.DateTimeField(default=timezone.now)
    land = models.ForeignKey(Land, models.SET_NULL, null=True, blank=True)
    quality = models.BooleanField()
    owner = models.ForeignKey(UserProfile, on_delete=models.PROTECT)
    income = models.FloatField(default=0)


    def __str__(self):
        return self.owner.username + " " + self.crop.name


class Kart(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    item = models.ForeignKey(Products, on_delete=models.SET_DEFAULT, default=-1)
    quantity = models.IntegerField()

    def __str__(self):
        return self.user.username + " " + self.item.name

class Ewallet(models.Model):
    user = models.OneToOneField(UserProfile, on_delete=models.CASCADE)
    amount = models.FloatField(default=0)

    def __str__(self):
        return self.user.username

class ew_transaction(models.Model):
    refno = models.CharField(max_length=20)
    user = models.ForeignKey(UserProfile, on_delete=models.PROTECT)
    amount = models.FloatField()
    date = models.DateTimeField(default=timezone.now)
    currrent_amount = models.FloatField(default=0)
    description = models.CharField(max_length=200)

RuralCaravan/members/templates/members/addnewleader.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Add New Leader</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
   <!-- Bootstrap core CSS -->
   <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
   <!-- Material Design Bootstrap -->
   <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
   <!--  custom styles  -->
   <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
   <style type="text/css">

      html,
      body,
      header,
      .carousel {
        height: 60vh;
      }

      @media (max-width: 740px) {
        html,
        body,
        header,
        .carousel {
          height: 100vh;
        }
      }

      @media (min-width: 800px) and (max-width: 850px) {
        html,
        body,
        header,
        .carousel {
          height: 100vh;
        }
      }

      @media (min-width: 800px) and (max-width: 850px) {
              .navbar:not(.top-nav-collapse) {
                  background:#295e10!important;
              }
          }
 footer {
   left: 0;
   bottom: 0;
   width: 100%;
  
}
    </style>
</head>

<body>

  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand" href="{% url 'home' %}">
        <strong>FPO PORTAL</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'meetings' %}" >Meetings</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'plans' %}">Plans</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'govtschemes' %}" >Government Schemes</a>
          </li>
             <li class="nav-item">
            <a class="nav-link" href="{% url 'produce' %}" >Production</a>
          </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'FPOLedger'%}">Ledger</a>
            </li>
        </ul>

        <!-- Right -->
         <ul class="navbar-nav nav-flex-icons">
            <li class="nav-item">
            <a href="{% url 'add_user' %}" class="nav-link" data-toggle="tooltip" title="Add New User">
             <i class="fas fa-user-plus"></i>
            </a>
          </li>
             <li class="nav-item">
            <a href="{% url 'transaction'%}" class="nav-link" data-toggle="tooltip" title="Transactions">
             <i class="fas fa-rupee-sign"></i>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'orders' %}" class="nav-link" data-toggle="tooltip" title="Orders">
             <i class="fas fa-shopping-cart"></i>
            </a>
          </li>
             <li class="nav-item">
            <a href="{% url 'products' %}" class="nav-link" data-toggle="tooltip" title="Products">
             <i class="fas fa-shopping-basket"></i>
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'fpo_statistics' %}" class="nav-link" data-toggle="tooltip" title="Statistics">
             <i class="fas fa-chart-bar"></i>
            </a>
          </li>
          <li class="nav-item active">
            <a href="{% url 'members' %}" class="nav-link border border-light rounded"
             >
              <i class="fas fa-user"></i>Members
            </a>
          </li>
		  <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}" >Logout</a>
          </li>


        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->

 

  <!--Main layout-->
  <main style="padding-top:10%">
    <div class="container" >

     
        <!--Section: Main features & Quick Start-->
      <section style="padding-bottom:5%">

        

        <!--Grid row-->
          <!--/Grid column-->

          <!--Grid column-->
          <div class="col-lg-6 col-md-12" style="margin:auto;">
			<!--Card-->
            <div class="card">

              <!--Card content-->
              <div class="card-body">

                 <form method="POST" enctype="multipart/form-data"> {% csrf_token %}

                  <!-- Heading -->
                  <h3 class="dark-grey-text text-center">
                    <strong>Add New Leader</strong>
                  </h3>
                  <hr>

                  <div class="md-form">
                    <i class="far fa-user-circle prefix green-text"></i>
                    <label for="id_user">User:</label>
                    <br><br>
                     <select name="user" required id="id_user" class="form-control">
                       <option value="" selected>---------</option>

                      {% for user in users %}
                         {% if user.category == "L" %}
                         <option value="{{user.id}}" >{{user.username}}</option>
                         {% endif %}
                      {% endfor %}

                    </select>





                  </div>
                  <div class="md-form">
				  <i class="far fa-user-circle prefix green-text"></i>

                    <input type="text"  class="form-control" name="first_name" maxlength="50" required id="id_first_name">
                    <label for="id_first_name">Enter First Name</label>
                  </div>
                  <div class="md-form">
				  <i class="far fa-user-circle prefix green-text"></i>

                    <input type="text"  class="form-control" name="last_name" maxlength="50" required id="id_last_name">
                    <label for="id_last_name">Enter Last Name</label>
                  </div>
                   <div class="md-form">
                    <i class="far fa-id-card prefix green-text"></i>
                    <input type="text"  class="form-control" name="aadhar" maxlength="12" required id="id_aadhar">
                    <label for="id_aadhar">Enter Aadhar</label>
                  </div>
                  <div class="md-form">
                    <i class="fas fa-phone prefix green-text"></i>
                    <input type="text"  class="form-control" name="contact" maxlength="10" required id="id_contact">
                    <label for="id_contact">Enter Contact Number</label>
                  </div>
				  <div class="md-form">
                    <i class="fas fa-map-marker-alt prefix green-text"></i>
                    <label for="id_district">District:</label>
                    <br><br>
                     <select name="district" required id="id_district" class="form-control" size="1">
                       <option value="" selected="selected">Select District</option>
                     </select>
                   </div>
                    <div class="md-form">
                    <i class="fas fa-map-marker-alt prefix green-text"></i>
                    <label for="id_village">Village:</label>
                    <br><br>
                     <select name="village" required id="id_village" class="form-control" size="1">
                       <option value="" selected="selected" >Select Village</option>
                     </select>
                   </div>
                   <div class="md-form">
                    <i class="far fa-user-circle prefix green-text"></i>
                    <input type="number" class="form-control" name="pin" maxlength="100" required id="id_pin">
                    <label for="id_pin">Enter PIN</label>
                  </div>
                   <div class="md-form">
                    <i class="fab fa-black-tie prefix green-text"></i>
                    <input type="text" class="form-control" name="" maxlength="20" id="id_profession">
                    <label for="id_profession">Enter Profession</label>
                  </div>
                   <div class="md-form">
                    <i class="fas fa-camera prefix green-text"></i>

                    <label for="id_photo">Photo</label>
                     <input type="file"   name="photo" accept="image/*"  id="id_photo" style="padding-left:10%;padding-bottom:2%">
                  </div>


                  <div class="text-center">
                    <button class="btn btn-green" onclick="checkLength()">ADD</button>

                  </div>
                    <!-- {{ form }} -->
                 </form>
                <!-- Form -->

           
          </div>
          <!--/Grid column-->

        </div>
        <!--/Grid row-->

      </section>

    </div>
  </main>
  <!--Main layout-->

  <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn" >

   

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2020 Copyright:
  Rural Caravan 
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->
  <script>
 function checkLength(){
    var aadhar = document.getElementById("id_aadhar").value;
    var flag1=0;
    var flag2=0;
    if(aadhar.length!=12){
        alert("Aadhar Number must be 12 digits long");
        flag1=1;
       return false;
    }
    var contact = document.getElementById("id_contact").value;
     if(contact.length!=10){
        alert("Contact Number must be 10 digits long");
        flag2=1;
        return false;
    }
    if(!flag1 && !flag2){
       return true;
    }
}
</script>
    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
      <!-- Initializations -->
  <script type="text/javascript">
    //new WOW().init();
  </script>
<script>
/*var stateObject = {
"district1": { "village1":"",
 "village2":"",
 "village3":"",
},
"district2": { "village4":"",
"village5":"",
"village6":"",
},
"district3": { "village7":"",
 "village8":"",
 "village9":"",
},
}*/
var stateObject = {{stateObject|safe}}
window.onload = function () {
var districts = document.getElementById("id_district"),
villages = document.getElementById("id_village");
for (var district in stateObject) {
districts.options[districts.options.length] = new Option(district, district);
}
districts.onchange = function () {
villages.length = 1; // remove all options bar first
if (this.selectedIndex < 1) return; // done
for (var vill in stateObject[this.value]) {
villages.options[villages.options.length] = new Option(vill, vill);
}
}
}
</script>
</body>

</html>

RuralCaravan/members/templates/members/addtest.html
<form method="POST" enctype="multipart/form-data"> 
  
    <!-- Security token -->
    {% csrf_token %} 
  
    <!-- Using the formset -->
    {{ form.as_p }} 
    <!-- {{ form.as_p }}  -->
    
      
    <input type="submit" value="Submit"> 
</form>

RuralCaravan/members/templates/members/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete</title>
</head>
<body>

</body>
</html>